// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnr8v3MyBO-5wQZUNWTB_LhpbW4bIZ4xI',
    appId: '1:1024268695178:web:9750071bcea8aee9b25f73',
    messagingSenderId: '1024268695178',
    projectId: 'maruapp-c46e5',
    authDomain: 'maruapp-c46e5.firebaseapp.com',
    storageBucket: 'maruapp-c46e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQY24ySmLI6G2qiRVZt2vKi-qfSmFMo8',
    appId: '1:1024268695178:android:0f8336e92ff17cc2b25f73',
    messagingSenderId: '1024268695178',
    projectId: 'maruapp-c46e5',
    storageBucket: 'maruapp-c46e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5-2WveP3n79kyk1pGbLJxYMhrlshGoI',
    appId: '1:1024268695178:ios:d60af7e5fa296d7ab25f73',
    messagingSenderId: '1024268695178',
    projectId: 'maruapp-c46e5',
    storageBucket: 'maruapp-c46e5.firebasestorage.app',
    iosBundleId: 'n',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5-2WveP3n79kyk1pGbLJxYMhrlshGoI',
    appId: '1:1024268695178:ios:670df5601347fd52b25f73',
    messagingSenderId: '1024268695178',
    projectId: 'maruapp-c46e5',
    storageBucket: 'maruapp-c46e5.firebasestorage.app',
    iosBundleId: 'y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnr8v3MyBO-5wQZUNWTB_LhpbW4bIZ4xI',
    appId: '1:1024268695178:web:b35c706bfd020dc0b25f73',
    messagingSenderId: '1024268695178',
    projectId: 'maruapp-c46e5',
    authDomain: 'maruapp-c46e5.firebaseapp.com',
    storageBucket: 'maruapp-c46e5.firebasestorage.app',
  );

}